// Разбор G-code: перенос prototype/tests/test_gcode.py и новые проверки.

#include <algorithm>
#include <chrono>
#include <cmath>
#include <format>
#include <numbers>
#include <string>

#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>

#include "kika/gcode/parser.hpp"

using Catch::Matchers::WithinAbs;
using Catch::Matchers::WithinRel;
using kika::gcode::parse;
using kika::gcode::ParseError;
using kika::gcode::Role;

namespace {

// Площадь сечения прутка 1,75 мм
const double FA = std::numbers::pi * (1.75 / 2) * (1.75 / 2);

double sum_length(const kika::gcode::Toolpaths& tp) {
  double l = 0;
  for (const auto& s : tp.segments) l += std::hypot(s.x1 - s.x0, s.y1 - s.y0);
  return l;
}

}  // namespace

TEST_CASE("Полный круг G2 с I/J, относительная экструзия", "[gcode][arc]") {
  const double L = 2 * std::numbers::pi * 10;
  const double e = L * 0.45 * 0.2 / FA;
  const std::string g = std::format(
      "; generated by OrcaSlicer\n"
      "M83\nG90\n;LAYER_CHANGE\n;Z:0.2\n;HEIGHT:0.2\nG1 Z0.2\n;TYPE:Outer wall\n"
      "G1 X110 Y100 F3000\nG2 X110 Y100 I-10 J0 E{:.6f}\n",
      e);
  const auto tp = parse(g);
  CHECK_THAT(tp.total_volume(), WithinRel(L * 0.45 * 0.2, 1e-3));
  CHECK_THAT(sum_length(tp), WithinRel(L, 2e-3));
  double xmin = 1e9, xmax = -1e9;
  for (const auto& s : tp.segments) {
    xmin = std::min({xmin, s.x0, s.x1});
    xmax = std::max({xmax, s.x0, s.x1});
  }
  CHECK(xmin < 90.1);
  CHECK(xmax > 109.9);
}

TEST_CASE("Дуга G3 через радиус R: направление обхода", "[gcode][arc]") {
  // полуокружность против часовой стрелки R=5 от (0,0) к (10,0): центр (5,0), дуга идёт через y<0
  const auto tp = parse("M83\n;LAYER_CHANGE\nG1 Z0.2\n;TYPE:Inner wall\nG1 X0 Y0\nG3 X10 Y0 R5 E1.0\n");
  double ymin = 1e9;
  for (const auto& s : tp.segments) ymin = std::min(ymin, s.y1);
  CHECK(ymin < -4.9);
}

namespace {

const char* kAbsoluteE =
    "M82\n"
    "G90\n"
    "G28\n"
    "G1 X0 Y0 Z0.3 E5 ; прочистка до первого слоя — должна отброситься\n"
    ";LAYER_CHANGE\n"
    ";Z:0.2\n"
    "G92 E0\n"
    "G1 Z0.2\n"
    ";TYPE:Outer wall\n"
    "G1 X10 Y0 E1.0\n"
    "G1 X10 Y10 E2.0\n"
    "G1 E1.2 ; откат\n"
    "G1 X0 Y10 ; перемещение без экструзии\n"
    "G1 E2.0 ; возврат\n"
    "G1 X0 Y0 E3.0\n"
    ";TYPE:Skirt\n"
    "G1 X-5 Y-5 E4.0\n"
    ";TYPE:Sparse infill\n"
    "G92 E0\n"
    "G1 X5 Y5 E0.5\n";

}  // namespace

TEST_CASE("Абсолютная экструзия, сбросы G92, откаты, юбка", "[gcode]") {
  const auto tp = parse(kAbsoluteE);
  REQUIRE(tp.size() == 4);  // 3 стенки + 1 заполнение
  CHECK_THAT(tp.total_volume(), WithinRel(3.5 * FA, 1e-9));
  CHECK(tp.info.excluded_volume > 0);
  CHECK(tp.segments[3].role == Role::Sparse);
}

TEST_CASE("Переводы строк Windows (CRLF) и старые Mac (CR)", "[gcode]") {
  std::string crlf, cr;
  for (const char* p = kAbsoluteE; *p; ++p) {
    if (*p == '\n') {
      crlf += "\r\n";
      cr += '\r';
    } else {
      crlf += *p;
      cr += *p;
    }
  }
  const auto a = parse(crlf);
  const auto b = parse(cr);
  CHECK(a.size() == 4);
  CHECK(b.size() == 4);
  CHECK_THAT(a.total_volume(), WithinRel(3.5 * FA, 1e-9));
  CHECK(a.info.n_lines == parse(kAbsoluteE).info.n_lines);
}

TEST_CASE("Относительные перемещения G91", "[gcode]") {
  const auto tp = parse("M83\n;LAYER_CHANGE\nG1 Z0.2\n;TYPE:Outer wall\nG1 X0 Y0\nG91\nG1 X10 E1\nG1 Y10 E1\n"
                        "G90\nG1 X0 Y0 E1\n");
  REQUIRE(tp.size() == 3);
  CHECK_THAT(tp.segments[0].x1, WithinAbs(10, 1e-12));
  CHECK_THAT(tp.segments[1].y1, WithinAbs(10, 1e-12));
  CHECK_THAT(tp.segments[2].x1, WithinAbs(0, 1e-12));
}

TEST_CASE("Маркеры Bambu Studio и тип пластика в конце файла", "[gcode]") {
  const auto tp = parse(
      "; BambuStudio 1.9\nM83\n; CHANGE_LAYER\n; Z_HEIGHT: 0.2\n; LAYER_HEIGHT: 0.2\nG1 Z0.2\n"
      "; FEATURE: Outer wall\nG1 X0 Y0\nG1 X10 Y0 E0.5\n; FEATURE: Prime tower\nG1 X20 Y0 E0.5\n"
      "; filament_type = PETG\n");
  REQUIRE(tp.size() == 1);
  CHECK(tp.info.filament_type == "PETG");
  CHECK(tp.info.slicer == "Bambu Studio");
  CHECK_THAT(tp.segments[0].h, WithinAbs(0.2, 1e-12));
}

TEST_CASE("Слова без пробелов: G1X10Y0E1", "[gcode]") {
  // Прототип читал «X10E1» как X = 10·10¹; правильно — X = 10 и E = 1.
  const auto tp = parse("M83\n;LAYER_CHANGE\nG1Z0.2\n;TYPE:Outer wall\nG1X0Y0\nG1X10Y0E1\n");
  REQUIRE(tp.size() == 1);
  CHECK_THAT(tp.segments[0].x1, WithinAbs(10, 1e-12));
  CHECK_THAT(tp.total_volume(), WithinRel(FA, 1e-12));
}

TEST_CASE("Номера строк N и контрольные суммы", "[gcode]") {
  const auto tp = parse("N1 M83*12\n;LAYER_CHANGE\nN3 G1 Z0.2*40\n;TYPE:Outer wall\n"
                        "N4 G1 X0 Y0*33\nN5 G1 X10 Y0 E1*97\n");
  REQUIRE(tp.size() == 1);
  CHECK_THAT(tp.segments[0].x1, WithinAbs(10, 1e-12));
  CHECK_THAT(tp.segments[0].z, WithinAbs(0.2, 1e-12));
}

TEST_CASE("Дюймы G20", "[gcode]") {
  const auto tp = parse("M83\nG20\n;LAYER_CHANGE\nG1 Z0.01\n;TYPE:Outer wall\nG1 X0 Y0\nG1 X1 Y0 E0.1\n");
  REQUIRE(tp.size() == 1);
  CHECK_THAT(tp.segments[0].x1, WithinAbs(25.4, 1e-12));
  CHECK_THAT(tp.total_volume(), WithinRel(2.54 * FA, 1e-12));
}

TEST_CASE("Нет экструзии детали — понятная ошибка", "[gcode]") {
  CHECK_THROWS_AS(parse("G28\nG1 X10 Y10\n"), ParseError);
  CHECK_THROWS_AS(parse(""), ParseError);
  // Только юбка — тоже ошибка
  CHECK_THROWS_AS(parse("M83\n;LAYER_CHANGE\n;TYPE:Skirt\nG1 X10 E1\n"), ParseError);
}

TEST_CASE("Подложка Cura (отрицательные слои) отбрасывается", "[gcode]") {
  const auto tp = parse(";Generated with Cura_SteamEngine 5.7\nM83\n;LAYER:-1\nG1 Z0.3\nG1 X10 Y0 E1\n"
                        ";LAYER:0\n;TYPE:WALL-OUTER\nG1 Z0.5\nG1 X20 Y0 E1\n");
  REQUIRE(tp.size() == 1);
  CHECK(tp.info.slicer == "Cura");
  CHECK(tp.segments[0].role == Role::OuterWall);
}

TEST_CASE("Финальный код и протирка сопла не входят в деталь", "[gcode]") {
  const auto tp = parse(
      "M83\n;LAYER_CHANGE\nG1 Z0.2\n;TYPE:Outer wall\nG1 X0 Y0\nG1 X10 Y0 E1\n"
      ";WIPE_START\nG1 X12 Y0 E0.2\n;WIPE_END\nG1 X10 Y10 E1\n"
      "; MACHINE_END_GCODE_START\nG1 X0 Y0 E5\n");
  REQUIRE(tp.size() == 2);
  CHECK_THAT(tp.total_volume(), WithinRel(2 * FA, 1e-12));
  CHECK_THAT(tp.info.excluded_volume, WithinRel(5.2 * FA, 1e-12));
}

TEST_CASE("Толщина и номера слоёв по фактическим Z", "[gcode][layers]") {
  const auto tp = parse("M83\n;LAYER_CHANGE\nG1 Z0.3\n;TYPE:Outer wall\nG1 X0 Y0\nG1 X10 Y0 E1\n"
                        ";LAYER_CHANGE\nG1 Z0.5\nG1 X0 Y0 E1\n;LAYER_CHANGE\nG1 Z0.7\nG1 X10 Y0 E1\n");
  REQUIRE(tp.size() == 3);
  CHECK(tp.info.n_layers == 3);
  CHECK_THAT(*tp.info.layer_height, WithinAbs(0.2, 1e-12));        // медиана шагов по Z
  CHECK_THAT(*tp.info.first_layer_height, WithinAbs(0.3, 1e-12));  // первый слой — от стола
  CHECK_THAT(tp.segments[0].h, WithinAbs(0.3, 1e-12));
  CHECK_THAT(tp.segments[1].h, WithinAbs(0.2, 1e-12));
  CHECK(tp.segments[0].layer == 0);
  CHECK(tp.segments[2].layer == 2);
  const auto bb = tp.bbox();
  CHECK_THAT(bb.min[2], WithinAbs(0.0, 1e-12));
  CHECK_THAT(bb.max[2], WithinAbs(0.7, 1e-12));
}

TEST_CASE("Настройки печати из комментариев", "[gcode][settings]") {
  const std::string body = "M83\n;LAYER_CHANGE\nG1 Z0.2\n;TYPE:Outer wall\nG1 X0 Y0\nG1 X10 Y0 E1\n";

  SECTION("OrcaSlicer: проценты, списки, первый пруток") {
    const auto tp = parse(body +
                          "; filament_diameter = 2.85,1.75\n; filament_diameter = 1.75\n"
                          "; sparse_infill_density = 15%\n; sparse_infill_pattern = gyroid\n"
                          "; wall_loops = 3\n; top_shell_layers = 5\n; bottom_shell_layers = 4\n"
                          "; line_width = 120%\n; nozzle_diameter = 0.4,0.6\n; filament_type = \"PETG;PLA\"\n");
    const auto& i = tp.info;
    CHECK(i.filament_diameter == 2.85);
    CHECK_THAT(*i.infill_density, WithinAbs(0.15, 1e-12));
    CHECK(i.infill_pattern == "gyroid");
    CHECK(i.wall_loops == 3);
    CHECK(i.top_layers == 5);
    CHECK(i.bottom_layers == 4);
    CHECK_FALSE(i.line_width.has_value());  // ширина в процентах не используется
    CHECK(i.nozzle_diameter == 0.4);
    CHECK(i.filament_type == "PETG");
    // пруток 2,85 мм: объём считается по нему
    CHECK_THAT(tp.total_volume(), WithinRel(std::numbers::pi * 2.85 * 2.85 / 4, 1e-12));
  }

  SECTION("PrusaSlicer: доля и миллиметры") {
    const auto tp = parse(body + "; fill_density = 0.2\n; perimeters = 2\n; extrusion_width = 0.45\n");
    CHECK_THAT(*tp.info.infill_density, WithinAbs(0.2, 1e-12));
    CHECK(tp.info.wall_loops == 2);
    CHECK(tp.info.line_width == 0.45);
  }

  SECTION("Cura: «Ключ: значение», плотность в процентах без знака") {
    const auto tp = parse(";Layer height: 0.12\n;infill_sparse_density = 20\n" + body);
    CHECK(tp.info.layer_height == 0.12);
    CHECK_THAT(*tp.info.infill_density, WithinAbs(0.2, 1e-12));
  }

  SECTION("Нет типа пластика и маркеров слоёв — предупреждения") {
    const auto tp = parse("M83\nG1 Z0.2\nG1 X0 Y0\nG1 X10 Y0 E1\n");
    REQUIRE(tp.info.warnings.size() == 2);
  }
}

TEST_CASE("200 000 строк разбираются быстро", "[gcode][speed]") {
  std::string g = "M83\n;LAYER_CHANGE\nG1 Z0.2\n;TYPE:Sparse infill\n";
  for (int k = 0; k < 200000; ++k)
    g += std::format("G1 X{:.3f} Y{:.3f} E0.0123\n", (k % 100) * 0.5, (k / 100) % 100 * 0.5);
  const auto t0 = std::chrono::steady_clock::now();
  const auto tp = parse(g);
  const double dt = std::chrono::duration<double>(std::chrono::steady_clock::now() - t0).count();
  CHECK(tp.size() == 199999);  // первое движение в (0,0) — без смещения, отрезка нет
  WARN(std::format("200 000 строк: {:.3f} с (прототип на Python — около 0,7 с)", dt));
}
