"""Проверки разбора G-code: дуги, режимы экструзии, отсечение служебных движений."""
import math
import os
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
from fdmfea.gcode import parse_gcode, classify_role, ROLE_OUTER_WALL, ROLE_SPARSE, ROLE_SOLID, ROLE_EXCLUDED, ROLE_INNER_WALL

FA = math.pi * (1.75 / 2) ** 2


def approx(a, b, rel=1e-3):
    assert abs(a - b) <= rel * max(abs(a), abs(b), 1e-9), (a, b)


def test_roles():
    assert classify_role("Outer wall") == ROLE_OUTER_WALL
    assert classify_role("External perimeter") == ROLE_OUTER_WALL
    assert classify_role("WALL-OUTER") == ROLE_OUTER_WALL
    assert classify_role("Inner wall") == ROLE_INNER_WALL
    assert classify_role("Overhang perimeter") == ROLE_INNER_WALL
    assert classify_role("Sparse infill") == ROLE_SPARSE
    assert classify_role("Internal infill") == ROLE_SPARSE
    assert classify_role("FILL") == ROLE_SPARSE
    assert classify_role("Internal solid infill") == ROLE_SOLID
    assert classify_role("Top surface") == ROLE_SOLID
    assert classify_role("Bridge infill") == ROLE_SOLID
    assert classify_role("Gap infill") == ROLE_SOLID
    assert classify_role("SKIN") == ROLE_SOLID
    for ex in ("Support", "Support interface", "Skirt", "Brim", "Skirt/Brim", "Prime tower", "Wipe tower", "Custom", "Ironing", "SUPPORT-INTERFACE"):
        assert classify_role(ex) == ROLE_EXCLUDED, ex


def test_arc_full_circle():
    # полный круг R=10 командой G2 с I/J, относительная экструзия
    L = 2 * math.pi * 10
    e = L * 0.45 * 0.2 / FA
    g = f"""; generated by OrcaSlicer
M83
G90
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
G1 Z0.2
;TYPE:Outer wall
G1 X110 Y100 F3000
G2 X110 Y100 I-10 J0 E{e:.6f}
"""
    tp = parse_gcode(g)
    approx(tp.total_volume(), L * 0.45 * 0.2)
    seglen = sum(math.hypot(a - b, c - d) for a, b, c, d in zip(tp.x1, tp.x0, tp.y1, tp.y0))
    approx(seglen, L, rel=2e-3)
    xs = list(tp.x0) + list(tp.x1)
    assert min(xs) < 90.1 and max(xs) > 109.9


def test_arc_R_form_and_direction():
    # полуокружность против часовой (G3) R=5 от (0,0) к (10,0): центр (5,0), дуга идёт через y<0
    g = """M83
;LAYER_CHANGE
G1 Z0.2
;TYPE:Inner wall
G1 X0 Y0
G3 X10 Y0 R5 E1.0
"""
    tp = parse_gcode(g)
    ys = list(tp.y1)
    assert min(ys) < -4.9, min(ys)


def test_absolute_e_and_resets():
    g = """M82
G90
G28
G1 X0 Y0 Z0.3 E5 ; прочистка до первого слоя — должна отброситься
;LAYER_CHANGE
;Z:0.2
G92 E0
G1 Z0.2
;TYPE:Outer wall
G1 X10 Y0 E1.0
G1 X10 Y10 E2.0
G1 E1.2 ; откат
G1 X0 Y10 ; перемещение без экструзии
G1 E2.0 ; возврат
G1 X0 Y0 E3.0
;TYPE:Skirt
G1 X-5 Y-5 E4.0
;TYPE:Sparse infill
G92 E0
G1 X5 Y5 E0.5
"""
    tp = parse_gcode(g)
    assert tp.n == 4, tp.n                 # 3 стенки + 1 заполнение
    approx(tp.total_volume(), 3.5 * FA)
    assert tp.info.excluded_volume > 0


def test_g91_relative_moves():
    g = """M83
;LAYER_CHANGE
G1 Z0.2
;TYPE:Outer wall
G1 X0 Y0
G91
G1 X10 E1
G1 Y10 E1
G90
G1 X0 Y0 E1
"""
    tp = parse_gcode(g)
    assert tp.n == 3
    approx(float(tp.x1[0]), 10)
    approx(float(tp.y1[1]), 10)
    approx(float(tp.x1[2]), 0)


def test_bambu_markers():
    g = """; BambuStudio 1.9
M83
; CHANGE_LAYER
; Z_HEIGHT: 0.2
; LAYER_HEIGHT: 0.2
G1 Z0.2
; FEATURE: Outer wall
G1 X0 Y0
G1 X10 Y0 E0.5
; FEATURE: Prime tower
G1 X20 Y0 E0.5
; filament_type = PETG
"""
    tp = parse_gcode(g)
    assert tp.n == 1
    assert tp.info.filament_type == "PETG"


def test_speed():
    # ~ 200 тыс. строк
    lines = ["M83", ";LAYER_CHANGE", "G1 Z0.2", ";TYPE:Sparse infill"]
    for k in range(200000):
        lines.append(f"G1 X{(k % 100) * 0.5:.3f} Y{(k // 100) % 100 * 0.5:.3f} E0.0123")
    t = time.time()
    tp = parse_gcode("\n".join(lines))
    dt = time.time() - t
    print(f"  200 000 строк: {dt:.2f} с ({tp.n} отрезков)")


if __name__ == "__main__":
    for name, fn in list(globals().items()):
        if name.startswith("test_") and callable(fn):
            fn()
            print("ok", name)
