"""Сверка разбора G-code: C++ (kika) против прототипа на Python (prototype/fdmfea/gcode.py).

Запуск:
    python tools/compare_with_prototype.py --kika build/linux-release/bin/kika [файлы.gcode ...]

Без файлов сверяются примеры прототипа и синтетические случаи из его тестов.
Нужен numpy. Сравниваются все отрезки (координаты, Z, толщина, объём, роль, слой)
и все сведения о печати. Выход с кодом 1, если есть расхождения.
"""
from __future__ import annotations

import argparse
import json
import math
import os
import subprocess
import sys
import tempfile

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "prototype"))
from fdmfea.gcode import load_gcode  # noqa: E402

FA = math.pi * (1.75 / 2) ** 2
_E_CIRCLE = 2 * math.pi * 10 * 0.45 * 0.2 / FA

# Синтетические случаи. Здесь только то, что обе версии обязаны разбирать одинаково
# (сознательные отличия C++ — слова без пробелов, номера строк N — сюда не входят).
SYNTHETIC = {
    "arc_full_circle": f"""; generated by OrcaSlicer
M83
G90
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
G1 Z0.2
;TYPE:Outer wall
G1 X110 Y100 F3000
G2 X110 Y100 I-10 J0 E{_E_CIRCLE:.6f}
""",
    "arc_R": """M83
;LAYER_CHANGE
G1 Z0.2
;TYPE:Inner wall
G1 X0 Y0
G3 X10 Y0 R5 E1.0
G2 X20 Y0 R-5 E1.0
""",
    "absolute_e": """M82
G90
G28
G1 X0 Y0 Z0.3 E5
;LAYER_CHANGE
;Z:0.2
G92 E0
G1 Z0.2
;TYPE:Outer wall
G1 X10 Y0 E1.0
G1 X10 Y10 E2.0
G1 E1.2
G1 X0 Y10
G1 E2.0
G1 X0 Y0 E3.0
;TYPE:Skirt
G1 X-5 Y-5 E4.0
;TYPE:Sparse infill
G92 E0
G1 X5 Y5 E0.5
""",
    "g91": """M83
;LAYER_CHANGE
G1 Z0.2
;TYPE:Outer wall
G1 X0 Y0
G91
G1 X10 E1
G1 Y10 E1
G90
G1 X0 Y0 E1
""",
    "bambu": """; BambuStudio 1.9
M83
; CHANGE_LAYER
; Z_HEIGHT: 0.2
; LAYER_HEIGHT: 0.2
G1 Z0.2
; FEATURE: Outer wall
G1 X0 Y0
G1 X10 Y0 E0.5
; FEATURE: Prime tower
G1 X20 Y0 E0.5
; filament_type = PETG
""",
    "cura_raft": """;Generated with Cura_SteamEngine 5.7
;Layer height: 0.12
;infill_sparse_density = 20
M83
;LAYER:-1
G1 Z0.3
G1 X10 Y0 E1
;LAYER:0
;TYPE:WALL-OUTER
G1 Z0.5
G1 X20 Y0 E1
;TYPE:FILL
G1 X20 Y10 E0.3
""",
    "end_and_wipe": """M83
;LAYER_CHANGE
G1 Z0.2
;TYPE:Outer wall
G1 X0 Y0
G1 X10 Y0 E1
;WIPE_START
G1 X12 Y0 E0.2
;WIPE_END
G1 X10 Y10 E1
; MACHINE_END_GCODE_START
G1 X0 Y0 E5
""",
    "layers_without_height": """M83
;LAYER_CHANGE
G1 Z0.3
;TYPE:Outer wall
G1 X0 Y0
G1 X10 Y0 E1
;LAYER_CHANGE
G1 Z0.5
G1 X0 Y0 E1
;LAYER_CHANGE
G1 Z0.7
G1 X10 Y0 E1
""",
    "settings": """M83
;LAYER_CHANGE
G1 Z0.2
;TYPE:Outer wall
G1 X0 Y0
G1 X10 Y0 E1
; filament_diameter = 2.85,1.75
; filament_diameter = 1.75
; sparse_infill_density = 15%
; sparse_infill_pattern = gyroid
; wall_loops = 3
; top_shell_layers = 5
; bottom_shell_layers = 4
; line_width = 120%
; nozzle_diameter = 0.4,0.6
; filament_type = "PETG;PLA"
""",
    "no_markers": """M83
G1 Z0.2
G1 X0 Y0
G1 X10 Y0 E1
G1 X10 Y10 E1
""",
    "inches": """M83
G20
;LAYER_CHANGE
G1 Z0.01
;TYPE:Outer wall
G1 X0 Y0
G1 X1 Y0 E0.1
""",
    "crlf": "M83\r\n;LAYER_CHANGE\r\n;HEIGHT:0.2\r\nG1 Z0.2\r\n;TYPE:Outer wall\r\nG1 X0 Y0\r\nG1 X10 Y0 E1\r\n",
}

INFO_FIELDS = ["slicer", "filament_type", "filament_diameter", "filament_density", "layer_height",
               "first_layer_height", "nozzle_diameter", "line_width", "infill_density", "infill_pattern",
               "wall_loops", "top_layers", "bottom_layers", "n_lines", "n_layers", "filament_used_mm",
               "settings", "warnings"]


def same(a, b) -> bool:
    if a is None or b is None:
        return a is None and b is None
    if isinstance(a, (float, int)) and isinstance(b, (float, int)) and not isinstance(a, bool):
        return math.isclose(float(a), float(b), rel_tol=1e-12, abs_tol=1e-12)
    return a == b


def run_cpp(kika: str, path: str, workdir: str):
    csv = os.path.join(workdir, "segments.csv")
    subprocess.run([kika, "segments", path, "-o", csv], check=True)
    out = subprocess.run([kika, "info", path, "--json"], check=True, capture_output=True, text=True,
                         encoding="utf-8").stdout
    seg = np.loadtxt(csv, delimiter=",", skiprows=1, ndmin=2)
    return seg, json.loads(out)


def compare(kika: str, path: str, workdir: str) -> list[str]:
    problems = []
    py = load_gcode(path)
    seg, info = run_cpp(kika, path, workdir)
    if len(seg) != py.n:
        return [f"число отрезков: C++ {len(seg)}, Python {py.n}"]
    cols = {"x0": py.x0, "y0": py.y0, "x1": py.x1, "y1": py.y1, "z": py.z, "h": py.h, "volume": py.vol}
    for k, (name, ref) in enumerate(cols.items()):
        if not np.allclose(seg[:, k], ref, rtol=1e-12, atol=1e-9):
            i = int(np.argmax(np.abs(seg[:, k] - ref)))
            problems.append(f"{name}: отрезок {i}: C++ {seg[i, k]!r}, Python {ref[i]!r}")
    if not np.array_equal(seg[:, 7].astype(int), py.role.astype(int)):
        problems.append("роли отрезков различаются")
    if not np.array_equal(seg[:, 8].astype(int), py.layer.astype(int)):
        problems.append("номера слоёв различаются")
    if not same(info["volume_mm3"], py.total_volume()):
        problems.append(f"объём: C++ {info['volume_mm3']!r}, Python {py.total_volume()!r}")
    if not same(info["excluded_volume_mm3"], py.info.excluded_volume):
        problems.append(f"отброшенный объём: C++ {info['excluded_volume_mm3']!r}, "
                        f"Python {py.info.excluded_volume!r}")
    for f in INFO_FIELDS:
        if not same(info[f], getattr(py.info, f)):
            problems.append(f"{f}: C++ {info[f]!r}, Python {getattr(py.info, f)!r}")
    return problems


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--kika", required=True, help="путь к программе kika")
    ap.add_argument("files", nargs="*", help="файлы G-code (по умолчанию — примеры и синтетика)")
    a = ap.parse_args()

    failed = 0
    with tempfile.TemporaryDirectory() as tmp:
        cases = []
        if a.files:
            cases = [(os.path.basename(f), f) for f in a.files]
        else:
            ex = os.path.join(ROOT, "prototype", "examples")
            cases = [(f, os.path.join(ex, f)) for f in sorted(os.listdir(ex)) if f.endswith(".gcode")]
            for name, text in SYNTHETIC.items():
                p = os.path.join(tmp, name + ".gcode")
                with open(p, "w", encoding="utf-8", newline="") as fh:
                    fh.write(text)
                cases.append((name, p))
        for name, path in cases:
            problems = compare(a.kika, path, tmp)
            if problems:
                failed += 1
                print(f"РАСХОЖДЕНИЕ  {name}")
                for p in problems:
                    print("    " + p)
            else:
                print(f"совпадает    {name}")
    print(f"\nИтого: {len(cases) - failed} из {len(cases)} совпадают с прототипом.")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
