"""Сверка C++ (kika) с прототипом на Python: разбор G-code и расчёт прочности.

Запуск:
    python tools/compare_with_prototype.py --kika build/linux-release/bin/kika [файлы.gcode ...]

1. Разбор G-code. Без файлов сверяются примеры прототипа и синтетические случаи из его тестов:
   все отрезки (координаты, Z, толщина, объём, роль, слой) и все сведения о печати.
2. Расчёт (`kika run`): задания кронштейнов, все виды нагрузок, консольная балка.
   Сравниваются итоги каждого случая (запас, перемещения, реакции, тексты, предупреждения),
   воксельная модель и поля по элементам (перемещения, запас, напряжения, вид разрушения),
   а также HTML-отчёт: данные 3D-просмотра и весь видимый текст (кроме даты, времени, версии).
   Оба решателя итерационные; чтобы сравнивать без их погрешности, обе версии решают
   с невязкой 1e-11 (обычно 1e-7). Допуск 1e-5 — из-за float32 в полях прототипа.

Нужны numpy и scipy (scipy — только для расчёта прототипом; без него шаг 2 пропускается
с ошибкой). --skip-analysis — только разбор G-code. Выход с кодом 1, если есть расхождения.
"""
from __future__ import annotations

import argparse
import json
import math
import os
import subprocess
import sys
import tempfile

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "prototype"))
from fdmfea.gcode import load_gcode  # noqa: E402

FA = math.pi * (1.75 / 2) ** 2
_E_CIRCLE = 2 * math.pi * 10 * 0.45 * 0.2 / FA

# Синтетические случаи. Здесь только то, что обе версии обязаны разбирать одинаково
# (сознательные отличия C++ — слова без пробелов, номера строк N — сюда не входят).
SYNTHETIC = {
    "arc_full_circle": f"""; generated by OrcaSlicer
M83
G90
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
G1 Z0.2
;TYPE:Outer wall
G1 X110 Y100 F3000
G2 X110 Y100 I-10 J0 E{_E_CIRCLE:.6f}
""",
    "arc_R": """M83
;LAYER_CHANGE
G1 Z0.2
;TYPE:Inner wall
G1 X0 Y0
G3 X10 Y0 R5 E1.0
G2 X20 Y0 R-5 E1.0
""",
    "absolute_e": """M82
G90
G28
G1 X0 Y0 Z0.3 E5
;LAYER_CHANGE
;Z:0.2
G92 E0
G1 Z0.2
;TYPE:Outer wall
G1 X10 Y0 E1.0
G1 X10 Y10 E2.0
G1 E1.2
G1 X0 Y10
G1 E2.0
G1 X0 Y0 E3.0
;TYPE:Skirt
G1 X-5 Y-5 E4.0
;TYPE:Sparse infill
G92 E0
G1 X5 Y5 E0.5
""",
    "g91": """M83
;LAYER_CHANGE
G1 Z0.2
;TYPE:Outer wall
G1 X0 Y0
G91
G1 X10 E1
G1 Y10 E1
G90
G1 X0 Y0 E1
""",
    "bambu": """; BambuStudio 1.9
M83
; CHANGE_LAYER
; Z_HEIGHT: 0.2
; LAYER_HEIGHT: 0.2
G1 Z0.2
; FEATURE: Outer wall
G1 X0 Y0
G1 X10 Y0 E0.5
; FEATURE: Prime tower
G1 X20 Y0 E0.5
; filament_type = PETG
""",
    "cura_raft": """;Generated with Cura_SteamEngine 5.7
;Layer height: 0.12
;infill_sparse_density = 20
M83
;LAYER:-1
G1 Z0.3
G1 X10 Y0 E1
;LAYER:0
;TYPE:WALL-OUTER
G1 Z0.5
G1 X20 Y0 E1
;TYPE:FILL
G1 X20 Y10 E0.3
""",
    "end_and_wipe": """M83
;LAYER_CHANGE
G1 Z0.2
;TYPE:Outer wall
G1 X0 Y0
G1 X10 Y0 E1
;WIPE_START
G1 X12 Y0 E0.2
;WIPE_END
G1 X10 Y10 E1
; MACHINE_END_GCODE_START
G1 X0 Y0 E5
""",
    "layers_without_height": """M83
;LAYER_CHANGE
G1 Z0.3
;TYPE:Outer wall
G1 X0 Y0
G1 X10 Y0 E1
;LAYER_CHANGE
G1 Z0.5
G1 X0 Y0 E1
;LAYER_CHANGE
G1 Z0.7
G1 X10 Y0 E1
""",
    "settings": """M83
;LAYER_CHANGE
G1 Z0.2
;TYPE:Outer wall
G1 X0 Y0
G1 X10 Y0 E1
; filament_diameter = 2.85,1.75
; filament_diameter = 1.75
; sparse_infill_density = 15%
; sparse_infill_pattern = gyroid
; wall_loops = 3
; top_shell_layers = 5
; bottom_shell_layers = 4
; line_width = 120%
; nozzle_diameter = 0.4,0.6
; filament_type = "PETG;PLA"
""",
    "no_markers": """M83
G1 Z0.2
G1 X0 Y0
G1 X10 Y0 E1
G1 X10 Y10 E1
""",
    "inches": """M83
G20
;LAYER_CHANGE
G1 Z0.01
;TYPE:Outer wall
G1 X0 Y0
G1 X1 Y0 E0.1
""",
    "crlf": "M83\r\n;LAYER_CHANGE\r\n;HEIGHT:0.2\r\nG1 Z0.2\r\n;TYPE:Outer wall\r\nG1 X0 Y0\r\nG1 X10 Y0 E1\r\n",
}

INFO_FIELDS = ["slicer", "filament_type", "filament_diameter", "filament_density", "layer_height",
               "first_layer_height", "nozzle_diameter", "line_width", "infill_density", "infill_pattern",
               "wall_loops", "top_layers", "bottom_layers", "n_lines", "n_layers", "filament_used_mm",
               "settings", "warnings"]


def same(a, b) -> bool:
    if a is None or b is None:
        return a is None and b is None
    if isinstance(a, (float, int)) and isinstance(b, (float, int)) and not isinstance(a, bool):
        return math.isclose(float(a), float(b), rel_tol=1e-12, abs_tol=1e-12)
    return a == b


def run_cpp(kika: str, path: str, workdir: str):
    csv = os.path.join(workdir, "segments.csv")
    subprocess.run([kika, "segments", path, "-o", csv], check=True)
    out = subprocess.run([kika, "info", path, "--json"], check=True, capture_output=True, text=True,
                         encoding="utf-8").stdout
    seg = np.loadtxt(csv, delimiter=",", skiprows=1, ndmin=2)
    return seg, json.loads(out)


def compare(kika: str, path: str, workdir: str) -> list[str]:
    problems = []
    py = load_gcode(path)
    seg, info = run_cpp(kika, path, workdir)
    if len(seg) != py.n:
        return [f"число отрезков: C++ {len(seg)}, Python {py.n}"]
    cols = {"x0": py.x0, "y0": py.y0, "x1": py.x1, "y1": py.y1, "z": py.z, "h": py.h, "volume": py.vol}
    for k, (name, ref) in enumerate(cols.items()):
        if not np.allclose(seg[:, k], ref, rtol=1e-12, atol=1e-9):
            i = int(np.argmax(np.abs(seg[:, k] - ref)))
            problems.append(f"{name}: отрезок {i}: C++ {seg[i, k]!r}, Python {ref[i]!r}")
    if not np.array_equal(seg[:, 7].astype(int), py.role.astype(int)):
        problems.append("роли отрезков различаются")
    if not np.array_equal(seg[:, 8].astype(int), py.layer.astype(int)):
        problems.append("номера слоёв различаются")
    if not same(info["volume_mm3"], py.total_volume()):
        problems.append(f"объём: C++ {info['volume_mm3']!r}, Python {py.total_volume()!r}")
    if not same(info["excluded_volume_mm3"], py.info.excluded_volume):
        problems.append(f"отброшенный объём: C++ {info['excluded_volume_mm3']!r}, "
                        f"Python {py.info.excluded_volume!r}")
    for f in INFO_FIELDS:
        if not same(info[f], getattr(py.info, f)):
            problems.append(f"{f}: C++ {info[f]!r}, Python {getattr(py.info, f)!r}")
    return problems


# ---------------------------------------------------------------------------
# Расчёт

# Задание из prototype/tests/test_all_loads.py: все виды нагрузок на кронштейне.
_HOLES = [{"hole": {"axis": "x", "center": [12.0, 15.0], "radius": 2.5}},
          {"hole": {"axis": "x", "center": [28.0, 15.0], "radius": 2.5}}]
_ARM_TOP = {"box": {"min": [55, 40, 0], "max": [70, 50, 30]}, "normal": "+y"}
_HANG = {"hole": {"axis": "y", "center": [62.0, 15.0], "radius": 4.0}}
ALL_LOADS_JOB = {
    "material": "PETG", "target_sf": 2.0,
    "fixtures": [{"where": _HOLES}, {"where": {"side": "xmin"}, "components": "x"}],
    "cases": [
        {"name": "Сила 30 Н", "loads": [{"type": "force", "where": _ARM_TOP, "vector": [0, -30, 0]}]},
        {"name": "Сила по величине и направлению",
         "loads": [{"type": "force", "where": _ARM_TOP, "value": 30, "direction": "-y"}]},
        {"name": "Груз 1 кг на вынесенной точке",
         "loads": [{"type": "mass", "where": _HANG, "kg": 1, "direction": "-y", "point": [62, 20, 15]}]},
        {"name": "Давление 0,05 МПа", "loads": [{"type": "pressure", "where": {"side": "ymax"}, "value": 0.05}]},
        {"name": "Кручение 2 Н·м",
         "loads": [{"type": "moment", "where": {"side": "xmax"}, "axis": "+x", "value": 2000}]},
        {"name": "Болт 40 Н", "loads": [{"type": "bearing", "where": _HANG, "vector": [0, -40, 0]}]},
        {"name": "Удар 0,3 кг с 100 мм",
         "loads": [{"type": "impact", "where": _ARM_TOP, "kg": 0.3, "height": 100, "direction": "-y"}]},
        {"name": "Прогиб конца 1 мм",
         "loads": [{"type": "displacement", "where": {"side": "xmax"}, "vector": [None, -1.0, None]}]},
        {"name": "Перегрузка 20 g", "loads": [{"type": "gravity", "g": [0, -20, 0]}]},
        {"name": "Вибрация 10 Н, 10^6 циклов", "duration": "cyclic", "cycles": 1e6,
         "loads": [{"type": "force", "where": _ARM_TOP, "vector": [0, -10, 0]}]},
        {"name": "Нагрев 60 °C, длительно, зажат", "duration": "long", "temperature": 60,
         "thermal_expansion": True,
         "fixtures": [{"where": _HOLES}, {"where": {"side": "xmin"}}, {"where": {"side": "xmax"}}],
         "loads": [{"type": "gravity", "g": [0, -1, 0]}]},
    ],
}


def _cantilever_job(upright: bool) -> dict:
    if upright:
        return {"material": "PLA", "cases": [{"name": "изгиб", "fixtures": [{"where": "zmin"}],
                                              "loads": [{"type": "force", "where": "zmax", "vector": [50, 0, 0]}]}]}
    return {"material": "PLA", "cases": [{"name": "изгиб", "fixtures": [{"where": "xmin"}],
                                          "loads": [{"type": "force", "where": "xmax", "vector": [0, 0, -50]}]}]}


def analysis_cases():
    ex = os.path.join(ROOT, "prototype", "examples")
    data = os.path.join(ROOT, "tests", "data")
    out = []
    for name in ("bracket_side", "bracket_upright"):
        with open(os.path.join(ex, name + ".job.json"), encoding="utf-8") as f:
            out.append((name, os.path.join(ex, name + ".gcode"), json.load(f), 40000, None))
    out.append(("все виды нагрузок", os.path.join(ex, "bracket_side.gcode"), ALL_LOADS_JOB, 25000, None))
    out.append(("балка плашмя", os.path.join(data, "cantilever_flat.gcode"), _cantilever_job(False), 120000, 1.0))
    out.append(("балка стоя", os.path.join(data, "cantilever_upright.gcode"), _cantilever_job(True), 120000, 1.0))
    return out


def compare_values(a, b, path: str) -> list[str]:
    """a — C++, b — прототип."""
    if isinstance(b, dict):
        if not isinstance(a, dict):
            return [f"{path}: C++ {a!r}, Python {b!r}"]
        out = []
        for k, v in b.items():
            if k == "solver":  # у решателей разное число итераций и время
                continue
            if k not in a:
                out.append(f"{path}.{k}: нет в C++")
            else:
                out += compare_values(a[k], v, f"{path}.{k}")
        return out
    if isinstance(b, (list, tuple)):
        if not isinstance(a, list) or len(a) != len(b):
            return [f"{path}: C++ {a!r}, Python {b!r}"]
        out = []
        for i, (x, y) in enumerate(zip(a, b)):
            out += compare_values(x, y, f"{path}[{i}]")
        return out
    if b is None or isinstance(b, (bool, str)):
        return [] if a == b else [f"{path}: C++ {a!r}, Python {b!r}"]
    if a is None or isinstance(a, (bool, str)):
        return [f"{path}: C++ {a!r}, Python {b!r}"]
    if math.isclose(float(a), float(b), rel_tol=1e-5, abs_tol=1e-9):
        return []
    return [f"{path}: C++ {a!r}, Python {float(b)!r}"]


SOLVER_TOL = 1e-11


def _strict_prototype_solver():
    """Прототип решает с той же строгой точностью, что и C++ при сверке."""
    import inspect

    from fdmfea import fem  # нужен scipy

    params = list(inspect.signature(fem.Solver.__init__).parameters)
    if params[4:8] != ["cells", "log", "tol", "springs"]:
        raise RuntimeError(f"изменилась сигнатура fem.Solver: {params}")
    fem.Solver.__init__.__defaults__ = (None, None, SOLVER_TOL, 1e-12)


# Точка экстремума может оказаться в другом, симметричном месте с тем же значением.
_TIES = [("sf_xyz", "sf"), ("sf_min_xyz", "sf_min"), ("max_disp_xyz", "max_disp"), ("max_disp_vec", "max_disp")]


def _accept_ties(cpp: dict, py: dict) -> list[str]:
    notes = []
    for where, value in _TIES:
        if where not in cpp or not compare_values(cpp[where], py[where], where):
            continue  # совпадает
        if compare_values(cpp[value], py[value], value):
            continue  # значение тоже другое — это настоящее расхождение
        if where == "max_disp_vec" and not math.isclose(math.hypot(*cpp[where]), cpp[value], rel_tol=1e-9):
            continue
        notes.append(f"{where}: другая точка с тем же значением ({cpp[where]} и {py[where]})")
        cpp[where] = py[where]
    return notes


def compare_analysis(kika: str, gcode: str, job: dict, max_elems: int, voxel, workdir: str) -> list[str]:
    _strict_prototype_solver()
    from fdmfea.analysis import Model, run

    jp = os.path.join(workdir, "job.json")
    with open(jp, "w", encoding="utf-8") as f:
        json.dump(job, f, ensure_ascii=False)
    out_json = os.path.join(workdir, "out.json")
    dump = os.path.join(workdir, "dump")
    report = os.path.join(workdir, "report.html")
    args = [kika, "run", gcode, jp, "--json", out_json, "--dump", dump, "--max-elems", str(max_elems), "--quiet",
            "--tol", str(SOLVER_TOL), "-o", report]
    if voxel:
        args += ["--voxel", str(voxel)]
    p = subprocess.run(args, capture_output=True, text=True, encoding="utf-8")
    if p.returncode != 0:
        return [f"kika run завершился с ошибкой: {p.stderr.strip()}"]
    with open(out_json, encoding="utf-8") as f:
        cpp = json.load(f)
    model = Model(gcode=gcode, voxel=voxel, max_elems=max_elems)
    analysis, res = run(model, job)

    def ld(name, dtype=np.float64):
        return np.fromfile(os.path.join(dump, name), dtype=dtype)

    problems = []
    vm = model.vm
    for name, x, y in [("плотность стенок", ld("voxel_rho_shell.bin"), vm.rho_shell),
                       ("плотность заполнения", ld("voxel_rho_sparse.bin"), vm.rho_sparse),
                       ("направления стенок", ld("voxel_hist_shell.bin"), vm.hist_shell.ravel()),
                       ("направления заполнения", ld("voxel_hist_sparse.bin"), vm.hist_sparse.ravel()),
                       ("номера вокселей", ld("voxel_flat.bin", np.int64), vm.flat())]:
        if x.shape != y.shape or not np.allclose(x, y, rtol=1e-9, atol=1e-12):
            problems.append(f"воксели, {name}: расходятся")
    if len(cpp) != len(res):
        return problems + [f"число случаев: C++ {len(cpp)}, Python {len(res)}"]
    for k, r in enumerate(res):
        name = r.summary["name"]
        for note in _accept_ties(cpp[k], r.summary):
            print(f"    {name}: {note}")
        problems += compare_values(cpp[k], r.summary, name)
        # поля прототипа хранятся во float32 — сравниваем относительно максимума
        u = ld(f"case{k}_u.bin").reshape(-1, 3)
        sf = ld(f"case{k}_sf.bin")
        fields = {
            "перемещения": (u, r.u),
            "1/запас": (1 / sf, 1 / r.sf.astype(np.float64)),
            "напряжения": (ld(f"case{k}_sigma.bin").reshape(-1, 6), r.sigma),
            "эквивалентное напряжение": (ld(f"case{k}_vm.bin"), r.vm),
        }
        for fname, (x, y) in fields.items():
            if x.shape != y.shape:
                problems.append(f"{name}: {fname}: размеры {x.shape} и {y.shape}")
                continue
            err = float(np.abs(x - y).max() / max(float(np.abs(y).max()), 1e-300))
            if err > 1e-5:
                problems.append(f"{name}: {fname}: отн. расхождение {err:.2e}")
        nmode = int((ld(f"case{k}_mode.bin", np.int8) != r.mode).sum())
        if nmode > 1e-4 * len(r.mode):
            problems.append(f"{name}: вид разрушения различается в {nmode} элементах")
    with open(report, encoding="utf-8") as f:
        problems += compare_report(f.read(), model, analysis, res, job, gcode)
    return problems


def _report_payload(html: str) -> dict:
    import base64
    import gzip
    import re

    m = re.search(r'window\.FDM_PAYLOAD = "([^"]*)"', html)
    return json.loads(gzip.decompress(base64.b64decode(m.group(1))))


def _report_text(html: str) -> str:
    """Видимая часть отчёта без даты, времени расчёта и версии программы."""
    import re

    body = html[html.index('<div class="page">'):html.index("<script>")]
    body = re.sub(r"\d\d\.\d\d\.\d{4} \d\d:\d\d", "", body)
    return re.sub(r"время расчёта [\d,]+ с · (fdmfea|kika) [\d.]+", "", body)


def compare_report(html_cpp: str, model, analysis, res, job: dict, gcode: str) -> list[str]:
    import base64

    from fdmfea.export import report_html

    html_py = report_html(model, analysis, res, job, title=job.get("title"), gcode_name=os.path.basename(gcode))
    pc, pp = _report_payload(html_cpp), _report_payload(html_py)
    problems = []
    skip = {"solver", "build_time", "total_time", "date", "version", "sf_xyz", "sf_min_xyz", "max_disp_xyz",
            "max_disp_vec"}  # точки экстремумов уже сверены выше (с учётом симметрии)

    def walk(a, b, path):
        if isinstance(b, dict):
            if not isinstance(a, dict):
                problems.append(f"отчёт {path}: C++ {a!r}")
                return
            is_model = "node_flat" in b
            is_case = "u" in b and "sel" in b
            for k, v in b.items():
                if k in skip:
                    continue
                if k not in a:
                    problems.append(f"отчёт {path}.{k}: нет в C++")
                elif (is_model and k in ("elems", "role", "rho", "node_flat")) or (is_case and k == "sel"):
                    if a[k] != v:
                        problems.append(f"отчёт {path}.{k}: различается")
                elif is_case and k in ("sf", "vm", "u", "mode"):
                    dt = np.uint8 if k == "mode" else np.float32
                    x = np.frombuffer(base64.b64decode(a[k]), dtype=dt).astype(float)
                    y = np.frombuffer(base64.b64decode(v), dtype=dt).astype(float)
                    if x.shape != y.shape:
                        problems.append(f"отчёт {path}.{k}: размеры {x.shape} и {y.shape}")
                    elif k == "mode":
                        if (x != y).sum() > 1e-4 * len(y):
                            problems.append(f"отчёт {path}.{k}: различается")
                    elif np.abs(x - y).max() > 1e-5 * max(float(np.abs(y).max()), 1e-30):
                        problems.append(f"отчёт {path}.{k}: расходится")
                else:
                    walk(a[k], v, f"{path}.{k}")
        elif isinstance(b, list):
            if not isinstance(a, list) or len(a) != len(b):
                problems.append(f"отчёт {path}: C++ {a!r}, Python {b!r}")
            else:
                for i, (x, y) in enumerate(zip(a, b)):
                    walk(x, y, f"{path}[{i}]")
        elif b is None or isinstance(b, (bool, str)):
            if a != b:
                problems.append(f"отчёт {path}: C++ {a!r}, Python {b!r}")
        elif a is None or isinstance(a, (bool, str)) or not math.isclose(float(a), float(b), rel_tol=2e-4,
                                                                          abs_tol=1e-4):
            # итоги в отчёте округлены до 4 знаков — отсюда допуск
            problems.append(f"отчёт {path}: C++ {a!r}, Python {b!r}")

    walk(pc, pp, "")
    if _report_text(html_cpp) != _report_text(html_py):
        problems.append("отчёт: видимый текст (шапка, карточки случаев, справка) различается")
    return problems[:20]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--kika", required=True, help="путь к программе kika")
    ap.add_argument("--skip-analysis", action="store_true", help="не сверять расчёт (только разбор G-code)")
    ap.add_argument("files", nargs="*", help="файлы G-code (по умолчанию — примеры и синтетика)")
    a = ap.parse_args()

    failed = 0
    with tempfile.TemporaryDirectory() as tmp:
        cases = []
        if a.files:
            cases = [(os.path.basename(f), f) for f in a.files]
        else:
            ex = os.path.join(ROOT, "prototype", "examples")
            cases = [(f, os.path.join(ex, f)) for f in sorted(os.listdir(ex)) if f.endswith(".gcode")]
            for name, text in SYNTHETIC.items():
                p = os.path.join(tmp, name + ".gcode")
                with open(p, "w", encoding="utf-8", newline="") as fh:
                    fh.write(text)
                cases.append((name, p))
        for name, path in cases:
            problems = compare(a.kika, path, tmp)
            if problems:
                failed += 1
                print(f"РАСХОЖДЕНИЕ  {name}")
                for p in problems:
                    print("    " + p)
            else:
                print(f"совпадает    {name}")
    print(f"\nРазбор G-code: {len(cases) - failed} из {len(cases)} совпадают с прототипом.")
    total_failed = failed

    if not a.skip_analysis and not a.files:
        print()
        acases = analysis_cases()
        failed = 0
        for name, gcode, job, max_elems, voxel in acases:
            with tempfile.TemporaryDirectory() as tmp:
                try:
                    problems = compare_analysis(a.kika, gcode, job, max_elems, voxel, tmp)
                except ImportError as e:
                    print(f"Расчёт прототипом невозможен: {e}. Установите: python -m pip install numpy scipy")
                    return 1
            if problems:
                failed += 1
                print(f"РАСХОЖДЕНИЕ  расчёт: {name}")
                for p in problems[:30]:
                    print("    " + p)
            else:
                print(f"совпадает    расчёт: {name}")
        print(f"\nРасчёт: {len(acases) - failed} из {len(acases)} совпадают с прототипом.")
        total_failed += failed
    return 1 if total_failed else 0


if __name__ == "__main__":
    sys.exit(main())
